### ISSUE TITLE
Images are not shown

### ISSUE THREAD

**Issue by vovkats** [dscout/wkhtmltopdf-buildpack#27]
@sorentwo my html page has images but this images are not shown in generated PDF. I had such problem when on my local machine was version of wkhtmltopdf installed via gem.

**Comment by sorentwo** [comment]
@vovkats That shouldn't have anything to do with wkhtmltopdf, it would be because the images can't resolve. Unless they are embedded in the html as data-uri you'll need to be sure they are publicly accessible.

I hope that helps. This is just a buildpack to install the wkhtmltopdf binary, it has nothing to do with integrating with Rails or applications.
